"""empty message

Revision ID: 2f34174e1845
Revises: 44352ebe8323
Create Date: 2024-11-20 01:09:39.415375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f34174e1845'
down_revision: Union[str, None] = '44352ebe8323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_pw', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=1), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
