"""empty message

Revision ID: 163caa0d71e5
Revises: f6628061d4d1
Create Date: 2024-12-03 03:18:46.117495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163caa0d71e5'
down_revision: Union[str, None] = 'f6628061d4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_table_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'tables', ['table_id'], ['table_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_table_id_fkey', 'orders', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
